name: plantagoda
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^0.6.7
  cupertino_icons: ^1.0.0
  flare_splash_screen: ^3.0.1
  font_awesome_flutter: ^8.8.1
  get_it: ^4.0.4
  google_fonts: ^1.1.1
  logger: ^0.9.2
  shared_preferences: ^0.5.12+4
  stacked: ^1.7.6
  stacked_localisation: null
  stacked_services: ^0.5.4+3
  stacked_themes: null

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^0.6.8

  # Generators
  build_runner: ^1.10.1
  stacked_localisation_generator: null

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/lang/
    - assets/images/icons/
    - assets/images/icons/categories/
    - assets/images/icons/tabs/
    - assets/images/icons/profile/
    - assets/images/icons/profile/
    - assets/images/
    - assets/images/country/
    - assets/images/favicon/
    - assets/images/background/
    - assets/animations/
    - assets/images/on_boarding/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
